runtime: nodejs12

instance_class: F1

# [START handlers]
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html
   secure: always

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
   secure: always
# [END handlers]
